### ISSUE TITLE
TypeError: 'type' object is not subscriptable when import nearest_advocate

### ISSUE THREAD

**Issue by beatriz10mar** [iot-salzburg/nearest-advocate#2]
**Describe the bug:**
When importing Nearest_Advocate, a TypeError occurs. I followed the instructions presented in the repository

```
pip install nearest_advocate
```
and
```
import numpy as np
import nearest_advocate
```

**Error Message:**
```
 Cell In[1], line 2
    import nearest_advocate
  File ~\anaconda3\lib\site-packages\nearest_advocate.py:15
    from nearest_advocate_numba import nearest_advocate as _nearest_advocate
  File ~\anaconda3\lib\site-packages\nearest_advocate_numba.py:95
    ) -> np.ndarray[(any, 2), np.float32]:
TypeError: 'type' object is not subscriptable
```

**System Specifications:**
OS: Windows (WindowsPE 64bit) 
Python 3.9.12
Numpy 1.20.3

**Comment by ChristophSchranz** [comment]
Hi @beatriz10mar ,
I'm sorry I could not reproduce this error.
It wonders me that this happens in Python 3.9, as it is suggested [here](https://stackoverflow.com/questions/71041586/typeerror-type-object-is-not-subscriptable) that it should work with 3.9 onwards.
Can you try a later Python version?

A workaround on my side would be to put the types into quotes as suggested [here](https://github.com/python/typing/issues/410) or to use `numpy.typing` suggested [here](https://stackoverflow.com/questions/68916893/typeerror-numpy-dtypemeta-object-is-not-subscriptable). Before solving, I just want to be sure what causes this issue.
